# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf7d795b80cc745c7d4bea48e819c56feb14625661e5e3141e0b262694d91c4c312eaed7201adb62f7ddcfd6b23831fe2ce0f5615ab9fd81def2fd06e21f43af

test:
  secret_key_base: 3eaaf928cb159114d1444e2aa1485b443225cd295e6e16f02931a017f4df8e7dcc52acee7733d2cb3241aacb3e22949e8964bc2a95c5a10346f1cdf056b87121

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
